name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Activate coverage package
        run: dart pub global activate coverage

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Check imports
        run: dart pub run import_sorter:main --exit-if-changed

      - name: Run tests
        run: dart test --test-randomize-ordering-seed random --coverage="coverage"

      - name: Generate coverage report
        run: format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
